import { integrations, type IntegrationCategory } from "@/config/integrationCatalog";

type Slug = (typeof integrations)[number]["slug"];
type Editorial = { why: string; scenarios: readonly [string, string, string] };

export const layerDescriptions: Record<IntegrationCategory, string> = {
  Telephony: "Telephony connects the agent to the phone network. Number ownership, call direction, routing, and human transfer all need to work before a voice workflow can serve callers.",
  Voices: "The voice layer turns an agent's response into speech. You can evaluate providers for natural delivery, speed, language coverage, and voice identity separately from the model that decides what to say.",
  Models: "The model layer interprets context, chooses a response, and decides when to use an approved tool. Prompt instructions and business rules are as important as the model name.",
  "SIP Trunking": "SIP trunking connects an existing carrier to the voice application. It keeps telephony ownership with your carrier while the agent handles conversation and business actions.",
  "Speech to Speech": "A speech-to-speech model hears and answers in a live audio session. Turn-taking, interruption handling, and tool use must be tested together on a real call.",
  "Speech Input": "Speech input converts the caller's audio into text for a pipeline agent. Recognition quality affects every answer and action that follows.",
  "CRM & Sales": "CRM and sales connections turn a conversation into a usable lead, activity, or next step. The agent should read only the fields it needs and write back confirmed outcomes.",
  Scheduling: "Scheduling tools let an agent offer real availability and record a confirmed appointment. Calendar rules, time zones, and conflict handling shape the caller experience.",
  Automation: "Automation moves structured call events and outcomes into the rest of your workflow. A clear event contract makes downstream actions reliable and observable.",
  Messaging: "Messaging closes the loop after a call or alerts a teammate during one. Recipient selection, consent, and the information shared should be explicit.",
  "Payments & Orders": "Payments and orders require a precise scope. Account billing, customer payment collection, and order actions are different workflows with different permissions.",
  "Build & Extend": "Developer connections let a voice agent use your own systems. Narrow credentials, predictable tool responses, and event delivery make custom actions safe to operate.",
};

export const integrationEditorial: Record<Slug, Editorial> = {
  twilio: { why: "Twilio is useful when your business already owns numbers or operates across several markets. The carrier route stays separate from the agent's conversational setup.", scenarios: ["Route an existing support number to an inbound agent.", "Run an approved outbound campaign with a known caller ID.", "Transfer a complex conversation to a human team."] },
  exotel: { why: "Exotel gives teams with Indian telephony an existing route into an AI call flow. Correct number assignment matters more than a generic provider connection.", scenarios: ["Answer after-hours enquiries on an Exotel number.", "Send overflow calls to a dedicated service agent.", "Route urgent calls from the agent to a person."] },
  vobiz: { why: "Vobiz appears as a telephony connection in Vozon's integration workspace. Linking the account gives the calling setup one place to track connection health.", scenarios: ["Connect a business telephony account to a workspace.", "Assign a number to a specific voice agent.", "Verify connection status before a campaign starts."] },
  elevenlabs: { why: "ElevenLabs gives teams a broad voice library and voice cloning options. The right choice depends on the language, brand tone, and speed required by live calls.", scenarios: ["Give a concierge agent a consistent brand voice.", "Preview natural delivery for multilingual scripts.", "Use an approved cloned voice where consent is documented."] },
  cartesia: { why: "Cartesia is an option when fast streamed speech matters in a live call. Voice quality should be judged on the same phone audio your customers hear.", scenarios: ["Keep short answers responsive during outbound qualification.", "Test a voice across a high-volume call script.", "Compare pacing with another text-to-speech provider."] },
  "sarvam-voice": { why: "Sarvam voices focus on Indian-language speech. They are useful when names, numbers, and regional delivery need local review.", scenarios: ["Speak appointment details in a supported Indian language.", "Read back names and addresses clearly.", "Keep regional support calls in the caller's language."] },
  openai: { why: "OpenAI models provide the reasoning layer for pipeline agents. Their role is to follow instructions, use context, and request only approved actions.", scenarios: ["Qualify a lead against a defined question set.", "Summarize a support request before transfer.", "Choose when an agent should call a calendar tool."] },
  "google-gemini": { why: "Gemini is another model choice for the response layer. Comparing the same call scenarios helps teams choose based on behavior instead of a model label.", scenarios: ["Answer questions grounded in approved business context.", "Handle a longer multi-step customer conversation.", "Decide when to use an external action tool."] },
  "sarvam-models": { why: "Sarvam models offer another path for multilingual reasoning. Regional language performance should be evaluated with real callers and business terms.", scenarios: ["Interpret an enquiry in a supported Indian language.", "Keep the agent's response in the chosen language.", "Extract structured fields from a local-language call."] },
  "sip-trunking": { why: "A bring-your-own trunk path lets teams retain their carrier arrangement while adding an AI agent. Routing and failover are part of the integration.", scenarios: ["Connect an existing company number without changing carriers.", "Send selected inbound traffic to an agent.", "Transfer a call back to an existing phone team."] },
  "openai-realtime": { why: "OpenAI Realtime handles live audio rather than separate transcription and speech stages. It should be judged on interruptions as well as answer quality.", scenarios: ["Answer a caller who changes direction mid-sentence.", "Run a low-latency interactive support call.", "Hand off to a person after an uncertain request."] },
  "gemini-live": { why: "Gemini Live is a direct audio conversation option. Teams can compare its voice, turn-taking, and tool behavior against their other agent modes.", scenarios: ["Hold a naturally paced voice conversation.", "Test mixed-language turns on a live call.", "Use a business action during an audio session."] },
  deepgram: { why: "Deepgram transcribes caller speech before the agent reasons about it. Phone audio quality, accents, and short replies are important test cases.", scenarios: ["Capture a noisy inbound support request.", "Recognize names and amounts in a qualification call.", "Feed a streaming transcript into a pipeline agent."] },
  "sarvam-speech": { why: "Sarvam speech input is relevant for Indian-language callers. Recognition needs to preserve local names and words that switch between languages.", scenarios: ["Transcribe a Hindi or regional-language enquiry.", "Capture addresses and proper names during a call.", "Support mixed-language conversations in a pipeline agent."] },
  "openai-transcription": { why: "OpenAI transcription can provide the text input for a pipeline agent. Compare its accuracy and delay on the calls your business actually receives.", scenarios: ["Convert a caller's request into agent context.", "Create a searchable transcript from phone audio.", "Extract details needed for a follow-up workflow."] },
  "elevenlabs-scribe": { why: "ElevenLabs Scribe adds another speech input option in the dashboard. The best fit depends on language coverage and transcript quality for your calls.", scenarios: ["Transcribe multilingual customer questions.", "Compare recognition on names and specialist terms.", "Feed live audio into a pipeline conversation."] },
  hubspot: { why: "HubSpot is most useful when a call should update an existing sales process. A clean contact match and concise outcome give the next teammate context.", scenarios: ["Create a new contact from a qualified call.", "Attach a call summary to an existing record.", "Trigger a sales follow-up after a positive answer."] },
  salesforce: { why: "Salesforce workflows often depend on required fields and permissions. Map the call outcome to a precise object and action before allowing writes.", scenarios: ["Update a lead after qualification.", "Create an activity for a completed conversation.", "Route a ready opportunity to the right owner."] },
  zoho: { why: "Zoho CRM can carry lead data and call outcomes into a team's existing sales view. Duplicate matching and field mapping deserve early testing.", scenarios: ["Capture a new lead from an inbound call.", "Append a disposition to a customer record.", "Create a follow-up task for a sales owner."] },
  "google-calendar": { why: "Google Calendar can give the agent live availability and a place to save confirmed appointments. It needs clear booking rules and resource selection.", scenarios: ["Offer available slots during an inbound call.", "Create an appointment after the caller confirms.", "Check the right calendar for a specific staff member."] },
  calendly: { why: "Calendly organizes appointment types and booking links. A voice agent should match the caller to the right event rather than share a generic link.", scenarios: ["Offer a consultation booking path.", "Send the right event link after qualification.", "Keep service duration aligned with the selected event type."] },
  "cal-com": { why: "Cal.com event types give callers a clear booking destination after a conversation. Match the event link to the service discussed, then let Cal.com show the available times.", scenarios: ["Share the correct consultation link after a qualifying call.", "Direct a caller to a team member's event page.", "Keep booking duration and time zone clear in the follow-up."] },
  "google-sheets": { why: "Google Sheets is a lightweight destination for structured call outcomes. It works best when the columns and ownership are defined before calls begin.", scenarios: ["Append lead details to a selected sheet.", "Record survey answers in consistent columns.", "Share call outcomes with an operations team."] },
  zapier: { why: "Zapier can receive an event from a configured API or webhook path and route it to other apps. Treat the event payload as a contract that can be retried.", scenarios: ["Start a follow-up task when a call ends.", "Move a structured outcome to another application.", "Notify a team when a lead meets a condition."] },
  gmail: { why: "Email follow-up is useful when a call needs a written next step. The recipient and content should come from confirmed call information.", scenarios: ["Send an approved appointment follow-up.", "Email an internal summary to a service team.", "Share next-step instructions after a completed call."] },
  slack: { why: "Slack gives the team a quick signal when a call needs attention. Alerts should be specific enough to act on without exposing unnecessary caller details.", scenarios: ["Notify an owner about a hot lead.", "Flag a failed tool action for review.", "Alert a team when a caller requests a person."] },
  razorpay: { why: "Razorpay Checkout in Vozon handles platform payments such as subscriptions and credit top-ups. It is separate from collecting a caller's business payment.", scenarios: ["Complete a Vozon subscription checkout.", "Top up calling credits in the billing workspace.", "Verify that a payment updated the account balance."] },
  "order-workflows": { why: "Order actions are business-specific API workflows. Keep the agent's scope narrow so it can answer a status question without changing an order unexpectedly.", scenarios: ["Read an order status after identity checks.", "Record a delivery exception for staff review.", "Update an order only after caller confirmation."] },
  "custom-api": { why: "A custom API lets the agent use a system that has no prebuilt connector. The tool contract should make allowed reads and writes explicit.", scenarios: ["Look up a customer account during a call.", "Create a support ticket from confirmed details.", "Return a safe fallback when an API times out."] },
  "vozon-ai": { why: "Vozon.ai brings agent setup, call context, and approved business actions into one workspace. Each agent should have a clear task, defined handoff, and reviewable outcome.", scenarios: ["Configure an agent for a specific inbound call flow.", "Use a native action to record a confirmed call outcome.", "Review call results and adjust the agent before publishing changes."] },
  webhooks: { why: "Webhooks deliver call events to your own service. They are useful when you want to react to outcomes without giving the agent direct write access.", scenarios: ["Process a call-ended event in an internal system.", "Store a transcript-ready notification.", "Retry a failed event delivery safely."] },
};
