"use client";
import {FormEvent,useState} from "react";
import {API_URL} from "@/lib/apiBase";
import styles from "./EnquiryChatbot.module.css";
const services=["AI Voice Agents","Customer Support Automation","Sales & Lead Qualification","Appointment Booking","Outbound Campaigns","Voice API & Integrations","Enterprise Solution","Other"];
export function EnquiryChatbot(){
 const[open,setOpen]=useState(false),[service,setService]=useState(services[0]),[sending,setSending]=useState(false),[caseNo,setCaseNo]=useState(""),[error,setError]=useState("");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch(API_URL+"/api/public/customer-cases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"service",name:form.get("name"),phone:form.get("phone"),service,message:"Customer requested information about "+service+".",sourcePage:window.location.href})});const result=await response.json();if(!response.ok)throw new Error(result.message||"Unable to submit your enquiry.");setCaseNo(result.caseNumber)}catch(caught){setError(caught instanceof Error?caught.message:"Please try again.")}finally{setSending(false)}}
 return <div className={styles.root}>{open?<section className={styles.card} aria-label="Submit a Vozon enquiry"><header><div><span>V</span><strong>Vozon Enquiry</strong></div><button onClick={()=>setOpen(false)} aria-label="Close enquiry">×</button></header>{caseNo?<div className={styles.success}><b>✓</b><h2>Thank you!</h2><p>Our team will call you shortly.</p><small>{caseNo}</small></div>:<form onSubmit={submit}><h2>How can we help?</h2><p>Select a service and leave your contact details.</p><label>Name<input name="name" required minLength={2} maxLength={80} placeholder="Your name"/></label><label>Phone number<input name="phone" required inputMode="tel" maxLength={20} placeholder="+91 98765 43210"/></label><label>Service<select value={service} onChange={event=>setService(event.target.value)}>{services.map(item=><option key={item}>{item}</option>)}</select></label>{error?<div className={styles.error}>{error}</div>:null}<button className={styles.submit} disabled={sending}>{sending?"Submitting...":"Request a call"}<span>→</span></button></form>}</section>:null}<button className={styles.launcher} onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-label="Open enquiry form"><span>💬</span>{open?"Close":"Talk to us"}</button></div>
}
